export enum statusOrderEnum {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  SHIPPED = 'SHIPPED',
  DELIEVERED = 'DELIEVERED',
  CANCELLED = 'CANCELLED',
}

export enum statusOrderAdminEnum {
  PENDING = 'PENDING',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}
