name: E-commerce CI/CD Pipeline

# Kích hoạt luồng chạy mỗi khi có code đẩy lên nhánh main
on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build & Push to Docker Hub
    # Mượn máy chủ Ubuntu mới nhất, siêu mạnh của GitHub để chạy
    runs-on: ubuntu-latest

    steps:
      # 1. Kéo code từ GitHub về máy chủ ảo này
      - name: Checkout Source Code
        uses: actions/checkout@v4

      # 2. Đăng nhập vào Docker Hub bằng chìa khóa em vừa nạp
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. Build Backend và đẩy lên Docker Hub
      - name: Build and Push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./HazHzel_Server
          push: true
          # Tên image sẽ có dạng: username/ecommerce-backend:latest
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ecommerce-backend:latest

      # 4. Build Frontend (Next.js) và đẩy lên Docker Hub
      - name: Build and Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./HazHzel_App
          push: true
          # Tên image sẽ có dạng: username/ecommerce-frontend:latest
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ecommerce-frontend:latest
