name: E-commerce CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build & Push to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Create Frontend .env for Build
        run: echo "NEXT_PUBLIC_BACKEND_URL=/api/v1" > ./HazHzel_App/.env.production

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./HazHzel_Server
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ecommerce-backend:latest

      - name: Build and Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./HazHzel_App
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ecommerce-frontend:latest

  deploy:
    name: Deploy to VPS
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Connect to VPS & Deploy
        uses: appleboy/ssh-action@v1.0.3

        env:
          FE_AUTH_SECRET: ${{ secrets.FE_AUTH_SECRET }}

          BE_PORT: ${{ secrets.BE_PORT }}
          BE_MONGODB_URI: ${{ secrets.BE_MONGODB_URI }}
          BE_JWT_SECRET: ${{ secrets.BE_JWT_SECRET }}
          BE_JWT_ACCESS_TOKEN_EXPIRED: ${{ secrets.BE_JWT_ACCESS_TOKEN_EXPIRED }}
          BE_MAILDEV_INCOMING_USER: ${{ secrets.BE_MAILDEV_INCOMING_USER }}
          BE_MAILDEV_INCOMING_PASS: ${{ secrets.BE_MAILDEV_INCOMING_PASS }}
          BE_CLOUDINARY_NAME: ${{ secrets.BE_CLOUDINARY_NAME }}
          BE_CLOUDINARY_API_KEY: ${{ secrets.BE_CLOUDINARY_API_KEY }}
          BE_CLOUDINARY_API_SECRET: ${{ secrets.BE_CLOUDINARY_API_SECRET }}
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            cd /home/thanh/HazHzel-Ecommerce

            # 1. CREATE .ENV FILE FOR FRONTEND
            echo "AUTH_SECRET=$FE_AUTH_SECRET" > HazHzel_App/.env
            echo "NEXT_PUBLIC_BACKEND_URL=/api/v1" >> HazHzel_App/.env
            echo "INTERNAL_BACKEND_URL=http://backend:8000/api/v1" >> HazHzel_App/.env

            # 2. CREATE .ENV FILE FOR BACKEND
            echo "PORT=$BE_PORT" > HazHzel_Server/.env
            echo "MONGODB_URI=$BE_MONGODB_URI" >> HazHzel_Server/.env
            echo "JWT_SECRET=$BE_JWT_SECRET" >> HazHzel_Server/.env
            echo "JWT_ACCESS_TOKEN_EXPIRED=$BE_JWT_ACCESS_TOKEN_EXPIRED" >> HazHzel_Server/.env
            echo "MAILDEV_INCOMING_USER=$BE_MAILDEV_INCOMING_USER" >> HazHzel_Server/.env
            echo "MAILDEV_INCOMING_PASS=$BE_MAILDEV_INCOMING_PASS" >> HazHzel_Server/.env
            echo "CLOUDINARY_NAME=$BE_CLOUDINARY_NAME" >> HazHzel_Server/.env
            echo "CLOUDINARY_API_KEY=$BE_CLOUDINARY_API_KEY" >> HazHzel_Server/.env
            echo "CLOUDINARY_API_SECRET=$BE_CLOUDINARY_API_SECRET" >> HazHzel_Server/.env

            # 3. PULL CODE AND OPERATE
            git pull origin main
            docker compose pull
            docker compose up -d --force-recreate

            # 4. DELETE ENV FILES FOR SECURITY
            rm HazHzel_App/.env HazHzel_Server/.env
